//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footbll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public System.Guid ForumId { get; set; }
        public string ForumTitle { get; set; }
        public string ForumContent { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string LastCommenter { get; set; }
        public Nullable<System.DateTime> LastCommentTime { get; set; }
        public int ReplyAmount { get; set; }
        public int CheckAmount { get; set; }
    }
}
