//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footbll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_Comment
    {
        public System.Guid CommentId { get; set; }
        public System.Guid ForumId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public int Numbers { get; set; }
    }
}
