//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footbll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public System.Guid UserId { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Head { get; set; }
        public Nullable<int> Sex { get; set; }
        public string FanAllianceId { get; set; }
        public string FanAllianceName { get; set; }
        public System.DateTime RegistTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    }
}
